export const KeypadTypeDef = {
    K0: 0,
    K1: 1,
    K2: 2,
    K3: 3,
    K4: 4,
    K5: 5,
    K6: 6,
    K7: 7,
    K8: 8,
    K9: 9,
    PLUS: 10,
    MINUS: 11,
    MULTIPLY: 12,
    DIVIDE: 13,
    PERCENT: 14,
    NEGATIVE_POSITIVE: 15,
    AC: 16,
    DOT: 17,
    EQUALS: 18,
}

export const KeypadDef = {
    [KeypadTypeDef.K0]: "0",
    [KeypadTypeDef.K1]: "1",
    [KeypadTypeDef.K2]: "2",
    [KeypadTypeDef.K3]: "3",
    [KeypadTypeDef.K4]: "4",
    [KeypadTypeDef.K5]: "5",
    [KeypadTypeDef.K6]: "6",
    [KeypadTypeDef.K7]: "7",
    [KeypadTypeDef.K8]: "8",
    [KeypadTypeDef.K9]: "9",
    [KeypadTypeDef.PLUS]: "+",
    [KeypadTypeDef.MINUS]: "-",
    [KeypadTypeDef.MULTIPLY]: "*",
    [KeypadTypeDef.DIVIDE]: "/",
    [KeypadTypeDef.PERCENT]: "%",
    [KeypadTypeDef.NEGATIVE_POSITIVE]: "+/-",
    [KeypadTypeDef.AC]: "AC",
    [KeypadTypeDef.DOT]: ".",
    [KeypadTypeDef.EQUALS]: "=",
}

export const DEFAULT_VALUE = KeypadDef[KeypadTypeDef.K0];